// <auto-generated />
using System;
using FashionShop.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionShop.Web.Migrations
{
    [DbContext(typeof(FashionShopDbContext))]
    [Migration("20260619041000_SeedMoreFashionData")]
    partial class SeedMoreFashionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionShop.Web.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Áo thun basic, oversize và local brand dễ phối đồ",
                            TenDanhMuc = "Áo thun"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Áo sơ mi đi học, đi làm, phong cách Hàn Quốc",
                            TenDanhMuc = "Áo sơ mi"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Jean ống rộng, baggy, straight-fit thời trang",
                            TenDanhMuc = "Quần jean"
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "Váy nữ, chân váy, đầm đi chơi và đi tiệc",
                            TenDanhMuc = "Váy"
                        },
                        new
                        {
                            Id = 5,
                            MoTa = "Áo khoác bomber, hoodie, blazer nam nữ",
                            TenDanhMuc = "Áo khoác"
                        },
                        new
                        {
                            Id = 6,
                            MoTa = "Túi, nón, thắt lưng và phụ kiện phối đồ",
                            TenDanhMuc = "Phụ kiện"
                        },
                        new
                        {
                            Id = 7,
                            MoTa = "Set phối sẵn cho đi học, đi làm, đi chơi",
                            TenDanhMuc = "Set đồ"
                        },
                        new
                        {
                            Id = 8,
                            MoTa = "Sản phẩm khuyến mãi nổi bật trong tuần",
                            TenDanhMuc = "Sale"
                        });
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Đà Nẵng",
                            Email = "admin@gmail.com",
                            HoTen = "Quản trị viên",
                            MatKhau = "123456",
                            SoDienThoai = "0900000000",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 1,
                            Gia = 150000m,
                            HinhAnh = "/images/products/ao-thun-trang.jpg",
                            MoTa = "Áo thun cotton mềm, form regular, dễ phối với jean hoặc kaki.",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 50,
                            TenSanPham = "Áo thun basic trắng"
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 2,
                            Gia = 250000m,
                            HinhAnh = "/images/products/ao-so-mi-xanh.jpg",
                            MoTa = "Áo sơ mi xanh pastel trẻ trung, phù hợp đi học, đi làm và chụp ảnh.",
                            NgayTao = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 30,
                            TenSanPham = "Áo sơ mi xanh pastel"
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 3,
                            Gia = 390000m,
                            HinhAnh = "/images/products/quan-jean-ong-rong.jpg",
                            MoTa = "Quần jean ống rộng form đẹp, phong cách Hàn Quốc, dễ phối sneaker.",
                            NgayTao = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 25,
                            TenSanPham = "Quần jean ống rộng"
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 5,
                            Gia = 420000m,
                            HinhAnh = "/images/products/hoodie-form-rong.svg",
                            MoTa = "Hoodie nỉ dày vừa, mũ đứng form, hợp thời tiết se lạnh.",
                            NgayTao = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 18,
                            TenSanPham = "Hoodie nỉ form rộng"
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 5,
                            Gia = 590000m,
                            HinhAnh = "/images/products/blazer-den.svg",
                            MoTa = "Blazer dáng suông, phối được với áo thun, sơ mi hoặc váy.",
                            NgayTao = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 12,
                            TenSanPham = "Blazer đen thanh lịch"
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 4,
                            Gia = 320000m,
                            HinhAnh = "/images/products/chan-vay-chu-a.svg",
                            MoTa = "Chân váy chữ A tôn dáng, chất vải đứng form, dễ phối áo sơ mi.",
                            NgayTao = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = false,
                            SoLuongTon = 20,
                            TenSanPham = "Chân váy chữ A kem"
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 7,
                            Gia = 520000m,
                            HinhAnh = "/images/products/set-croptop-quan-suong.svg",
                            MoTa = "Set đồ phối sẵn năng động, phù hợp đi chơi cuối tuần.",
                            NgayTao = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 15,
                            TenSanPham = "Set áo croptop và quần suông"
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 6,
                            Gia = 180000m,
                            HinhAnh = "/images/products/tui-tote-canvas.svg",
                            MoTa = "Túi tote canvas dày, đựng laptop nhỏ, sách vở và phụ kiện hằng ngày.",
                            NgayTao = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = false,
                            SoLuongTon = 45,
                            TenSanPham = "Túi tote canvas"
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 1,
                            Gia = 230000m,
                            HinhAnh = "/images/products/ao-thun-graphic.svg",
                            MoTa = "Áo thun oversize in graphic tối giản, chất cotton co giãn nhẹ.",
                            NgayTao = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 36,
                            TenSanPham = "Áo thun oversize graphic"
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 3,
                            Gia = 360000m,
                            HinhAnh = "/images/products/quan-kaki-suong.svg",
                            MoTa = "Quần kaki ống suông màu be, phù hợp style tối giản và lịch sự.",
                            NgayTao = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = false,
                            SoLuongTon = 22,
                            TenSanPham = "Quần kaki ống suông"
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 4,
                            Gia = 450000m,
                            HinhAnh = "/images/products/dam-midi-hoa.svg",
                            MoTa = "Đầm midi hoa nhí nhẹ nhàng, hợp đi cafe, dạo phố hoặc du lịch.",
                            NgayTao = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = true,
                            SoLuongTon = 14,
                            TenSanPham = "Đầm midi hoa nhí"
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 6,
                            Gia = 160000m,
                            HinhAnh = "/images/products/mu-bucket.svg",
                            MoTa = "Mũ bucket basic chống nắng nhẹ, phối cùng streetwear hoặc casual.",
                            NgayTao = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiBat = false,
                            SoLuongTon = 40,
                            TenSanPham = "Mũ bucket basic"
                        });
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("FashionShop.Web.Models.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionShop.Web.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.DonHang", b =>
                {
                    b.HasOne("FashionShop.Web.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.SanPham", b =>
                {
                    b.HasOne("FashionShop.Web.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionShop.Web.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
